# This file was auto-generated by salt's setup on Thu, 30 Jul 2015 22:42:32 +1000. (Date from debian changelog)

ROOT_DIR = None
CONFIG_DIR = None
CACHE_DIR = None
SOCK_DIR = None
SRV_ROOT_DIR= None
BASE_FILE_ROOTS_DIR = None
BASE_PILLAR_ROOTS_DIR = None
BASE_MASTER_ROOTS_DIR = None
LOGS_DIR = None
PIDFILE_DIR = None
__source_package_version__ = "2015.5.3+ds-1trusty1"
