# This file was auto-generated by salt's setup on Tuesday, 07 July 2015 @ 21:07:09 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 5, 3, 0, 0, 0, None)
